[package]
name = "kordoc-hancom"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
aes.workspace = true
cbc.workspace = true
flate2.workspace = true
kordoc-ir = { path = "../kordoc-ir", version = "=0.1.0" }
kordoc-tables = { path = "../kordoc-tables", version = "=0.1.0" }
pbkdf2.workspace = true
quick-xml.workspace = true
serde.workspace = true
sha1.workspace = true
sha2.workspace = true
subtle.workspace = true
zip.workspace = true
